import { escapeHtml } from '../../lib/dom.js';
import { renderRelationArrow } from './RelationArrow.js';

export function renderSVRelationJudge({ noun, verb, relation = '', form = '', forms = [], prompt = '名詞がこの動作をする？', questionId = 'sv', selectedNodes = {} } = {}) {
  const nounSelected = selectedNodes.noun === true;
  const verbSelected = selectedNodes.verb === true;
  const nodesReady = nounSelected && verbSelected;
  const node = (side, text) => `<button type="button" class="spec-node-button${selectedNodes[side] ? ' is-selected' : ''}" data-spec-sv-node="${escapeHtml(questionId)}:${side}" aria-pressed="${selectedNodes[side] === true}">${escapeHtml(text)}</button>`;
  const relationControls = nodesReady ? `<div class="spec-sv-relation-choices" data-spec-sv-relation-choices><p class="spec-sv-prompt">${escapeHtml(noun)} が ${escapeHtml(verb)} <strong>する？ される？</strong></p><button type="button" class="spec-choice${relation === 'active' ? ' is-selected' : ''}" data-spec-sv-relation="${escapeHtml(questionId)}:active" aria-pressed="${relation === 'active'}">する</button><button type="button" class="spec-choice${relation === 'passive' ? ' is-selected' : ''}" data-spec-sv-relation="${escapeHtml(questionId)}:passive" aria-pressed="${relation === 'passive'}">される</button></div>` : `<p class="spec-sv-prompt">${escapeHtml(prompt)}<br />名詞と元の動詞をクリックしてから、関係を選びます。</p>`;
  return `<div class="spec-sv-judge" data-spec-sv-judge><div class="spec-sv-targets">${node('noun', noun)}<span>＋</span>${node('verb', verb)}</div>${relation && nodesReady ? renderRelationArrow({ from: relation === 'active' ? noun : verb, to: relation === 'active' ? verb : noun, label: relation === 'active' ? 'ACTIVE / する' : 'PASSIVE / される', direction: 'forward' }) : ''}${relationControls}${relation && nodesReady ? `<div class="spec-form-choice" data-spec-sv-form-choice><p>STEP 2：分詞の形を選ぶ</p>${forms.map((item) => `<button type="button" class="spec-choice${form === item.id ? ' is-selected' : ''}" data-spec-sv-form="${escapeHtml(questionId)}:${escapeHtml(item.id)}" aria-pressed="${form === item.id}">${escapeHtml(item.text ?? item.id)}</button>`).join('')}</div>` : ''}${form ? `<p class="spec-sv-result" role="status" aria-live="polite">${escapeHtml(form)}</p>` : ''}</div>`;
}
